import { Poppins } from 'next/font/google';
import "./globals.css";
import Header from "@/components/Header/Header";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400','800'], // Choose the weights you need
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}  antialiased`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
